-- MySQL Script generated by MySQL Workbench
-- Wed Aug 12 10:29:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bmart-2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bmart-2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bmart-2` DEFAULT CHARACTER SET utf8 ;
USE `bmart-2` ;

-- -----------------------------------------------------
-- Table `bmart-2`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmart-2`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `img_url` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `removed` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bmart-2`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmart-2`.`banner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `img_url` VARCHAR(255) NOT NULL,
  `removed` TINYINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bmart-2`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmart-2`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  `subcategory_id` INT NOT NULL,
  `discount` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `max_quantity` INT NOT NULL,
  `stock` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `removed` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bmart-2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmart-2`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `removed` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bmart-2`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmart-2`.`order` (
  `created_at` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `product_id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_order_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bmart-2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `bmart-2`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bmart-2`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmart-2`.`cart` (
  `created_at` DATETIME NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`user_id`, `product_id`),
  INDEX `fk_cart_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bmart-2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `bmart-2`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bmart-2`.`dib`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmart-2`.`dib` (
  `created_at` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `product_id`),
  INDEX `fk_dib_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_dib_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `bmart-2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dib_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `bmart-2`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bmart-2`.`search_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmart-2`.`search_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_search_history_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_search_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bmart-2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bmart-2`.`sub_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmart-2`.`sub_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `removed` TINYINT NOT NULL,
  `category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sub_category_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_sub_category_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_sub_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `bmart-2`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sub_category_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `bmart-2`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
