name: Deploy to Amazon ECS
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: update client and server
      run: |
        cd client
        yarn install
        yarn build
        cd ..
        cd server
        yarn install
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        aws_s3_bucket: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        SOURCE_DIR: "client/build"
